### ISSUE TITLE
MAS v9 CLI Install fails executing the app-cfg-manage task

### ISSUE THREAD

**Issue by diegovisentin** [ibm-mas/installer#1074]
I am trying to install MAS Manage v9 with DB2 outside OCP. The pipeline always fails in the task "app-cfg-manage" during the "validate and parse jdbc connection parameter". Printing the variable bindingData.jdbc ("jdbc binding data") in the log shows that the reason is the lack of minimum data such as the jdbc url. 
This is strange because the CR JdbcCfg is correctly compiled.
Do you have any idea why this might happen and if possible how to address this issue?

[dvmas90-entitymgr-ws-79c86d95c6-l2fj6-manager-1.log](https://github.com/user-attachments/files/16038278/dvmas90-entitymgr-ws-79c86d95c6-l2fj6-manager-1.log)

**Comment by durera** [comment]
As you say the JdbcCfg looks healthy this seems like a defect inside the product itself, rather than anything we can address in the CLI.

I think to address this we need to get a support ticket opened and attach the output from `mas must-gather` to it.

**To speed things up please provide a link to this issue in the support ticket.**

Once we have the must-gather the things for support to be looking at will be the reconcile logs of the manage workspace entity manager and the jdbccfg entity manager

From the log already shared here we can see the binding data is missing most of the required information:

```
 {'scope': 'workspace-application', 'driveroptions': []}
```

We need to first verify this information is correctly represented in the status subresource of the jdbccfg (which is where the binding will get it from - it doesn't matter if it's in the spec, it has to be preresented in the status).  If not then the problem lies in the jdbccfg layer, and probably means it failed to connect to the db2 instance to verify the connection (and should have thrown an error somewhere).

If the status resource is as expected then we need to poke around the MAS internal API logs to debug what's happening when Manage is creating the binding.
