### ISSUE TITLE
Incorrect yq version

### ISSUE THREAD

**Issue by xuchixc** [ibm-mas/installer#1096]
In the laest version of MAS CLi container image, the `yq` version is not correct. 
I found there are two `yq` commands, the correct version of `yq` should be `v4.35.1` which is located at `/usr/bin/yq`.
The current found `yq` version is `3.2.2` which is located at `/opt/app-root/bin/yq`
We need to keep the latest yq version `v4.35.1` , otherwise some existing codes which dependent on yq `v4.x` will be failed. 

```
[ibmmas/cli:10.0.5]mascli$ yq --version
yq 3.2.2
[ibmmas/cli:10.0.5]mascli$ which yq
/opt/app-root/bin/yq
[ibmmas/cli:10.0.5]mascli$ whereis yq
yq: /usr/bin/yq /opt/app-root/bin/yq
```

**Comment by xuchixc** [comment]
Did some tests, this issue was involved in `10.0.3` 

[ibmmas/cli:10.0.3]mascli$ which yq
/opt/app-root/bin/yq

[ibmmas/cli:10.0.2]mascli$ which yq
/usr/bin/yq

**Comment by durera** [comment]
@whitfiea It looks like the version of yq being installed via pypi in https://github.com/ibm-mas/cli-base/pull/8 is conflicting with the version of yq installed already via 

- https://github.com/ibm-mas/cli-base/blob/b293e16a6adf22ee868c69391da7388e048ba9c1/image/cli-base/install/requirements.txt#L11 (installs yq v3)
- https://github.com/ibm-mas/cli-base/blob/b293e16a6adf22ee868c69391da7388e048ba9c1/image/cli-base/install/install-yq.sh (installs yq v4)

**Comment by whitfiea** [comment]
It is different implementations of yq rather than just different versions. The version installed via pip is this one https://pypi.org/project/yq/ which is the `kislyuk` implementation. The yq installed via https://github.com/ibm-mas/cli-base/blob/b293e16a6adf22ee868c69391da7388e048ba9c1/image/cli-base/install/install-yq.sh is the `mikefarah` version.

The conflict is that we have code now in the cli that assumes that `yq` is the mikefarah version, and code in the `gitops` branch that assumes that `yq` is the kislyuk version.

We should standardise on the mikefarah version and actually have an issue on the backlog to do that https://jsw.ibm.com/browse/MASCORE-2119

**Comment by whitfiea** [comment]
PR to resolve this is here https://github.com/ibm-mas/cli-base/pull/9
