### ISSUE TITLE
Synchronize MAS and CLI version numbers

### ISSUE THREAD

**Issue by nogayama** [ibm-mas/installer#1166]
### Feature and motivation

Currently the version number of MAS and CLI are independently allocated. So It is hard to find the stable CLI version to install specific MAS version. If we assign the version number with the corresponding MAS that can be installed by the CLI, It is very use full to identify which CLI should be used.

### Usage example

For example, if MAS version is `v9.1.1`, and core implementation of CLI version is `1.2.3`, then CLI version can be `v9.1.1.cli.1.2.3`.

**Comment by durera** [comment]
The version of MAS has no direct bearing on the version of the CLI to use/there is not a 1:1 relationship.  

We publish the recommended versions of the CLI to use for installing older catalogs so that customers can use versions of the CLI that were tested with the same catalog they want to use; generally speaking any version of the CLI will support the most recent 4 months worth of catalogs, so when installing older catalogs for whatever reason, older versions of the CLI should be used.

Use the information here to match the catalog you are using with the recommended version of the CLI: https://ibm-mas.github.io/cli/catalogs/#static-catalogs

![image](https://github.com/user-attachments/assets/9440d496-bb1e-47c3-97b2-24a79620afa7)
