### ISSUE TITLE
db2 operator version is old

### ISSUE THREAD

**Issue by aroute** [ibm-mas/installer#122]
DB2 [version](https://www.ibm.com/docs/en/db2/11.5?topic=deployments-db2-red-hat-openshift#concept_bq1_v4r_hlb__table_s5y_qpc_54b) hardcoded as default in the db2 role is old. The maximo catalog doesn't have the needed operator version to bring it to `11.5.7.0-cn7`. Any way this can be changed? In addition, [this](https://ibm-mas.github.io/cli/catalogs/v8-221129-amd64/) information doesn't seems to be logical, given that everything in MAS 8.9 is supporting OCP 4.10 (except for DB2)  : 
> DB2, which is installed with ibm-db2u-operator, is supported on OpenShift Container Platform versions 4.6-4.9 only.

**Comment by durera** [comment]
> DB2, which is installed with ibm-db2u-operator, is supported on OpenShift Container Platform versions 4.6-4.9 only
Unfortunately Db2 supported OCP version is beyond our control.  It is certainly troublesome/bizarre that the version support is falling behind for this dependency.  It works just fine though from all our testing, it could just be their documentation is our of date.

> The maximo catalog doesn't have the needed operator version to ...
We've been seeing issues with newer operator versions from the IBM Operator Catalog in our testing for the last few months, which is why the content in the Maximo curated catalog hasn't changed for a while now.  We are working on bringing updated operator packages to the next monthly update though.

**Comment by andrercm** [comment]
Thanks @aroute for your feedback, we have moved default DB2 version in cli from `11.5.7.0-cn2` to `11.5.7.0-cn4` at this point and have plans to upgrade it to `11.5.7.0-cn7` along with the ansible-devops support extension over the next month, therefore I believe we'll resolve your request by April-May timeframe.
