### ISSUE TITLE
mas mirror-image command gives error "choose_mas_version: command not found"

### ISSUE THREAD

**Issue by mattlrx** [ibm-mas/installer#1387]
### MAS CLI version

11.11.2

### CLI function used

mirror-images

### What happened?

on step 4 we see the following error:
4) Configure Static Catalog Version
/mascli/functions/mirror_images: line 365: choose_mas_version: command not found

### Relevant log output

```shell
4) Configure Static Catalog Version
/mascli/functions/mirror_images: line 365: choose_mas_version: command not found
```

**Comment by IanBoden** [comment]
Yip this is broken. You should be able to workaround it using something like:
export MAS_CATALOG_VERSION=v9-241107-amd64
export MAS_CHANNEL=9.0.x

Or use non-interactive mode as described via
mas mirror-images --help

If using the interactive mode with exporting the channel and version, there is some weird behaviour to watch out for. If you export the values and then run the mirror and get past step 4 it will save the values into:
/opt/app-root/src/.ibm-mas/cli.env
So even if you export new values (because you've changed your mind or are trying to mirror multiple different channels) it will reuse the old values, you can either edit or delete the cli.env file to fix that.
