### ISSUE TITLE
Custom storage class support for KAFKA storage

### ISSUE THREAD

**Issue by sauraba** [ibm-mas/installer#81]
https://github.com/ibm-mas/ansible-devops/blob/master/ibm/mas_devops/roles/kafka/tasks/determine-storage-classes.yml
going by this supported_storage_classes: are [ibmc-block-gold, ocs-storagecluster-ceph-rbd, managed-premium] 

 Customer has NFS based block storage and that is not being picked by the one-click install. Using one-click  install, we provided the relevant storage class and see KAFKA_STORAGE_CLASS=trunas-iscsi-nfs  env variable populated. However, zookeeper_storage_class is not assigned the storage class.

Had discussion with David Parker and fix  to support custom classes has to be implemented here : https://github.com/ibm-mas/cli/blob/master/tekton/pipelines/install.yaml#L458-L481 -- broken link - replacement: https://github.com/ibm-mas/cli/blob/master/tekton/src/pipelines/install.yml.j2

**Comment by andrercm** [comment]
Thanks @sauraba for your feedback, indeed there should be a way for you to setup your own storage classes for Kafka.
We will work on this issue within the next development cycles for cli.

**Comment by JonahLuckett** [comment]
This issue looks to have been solved independently since this issue was opened

When using the CLI I altered the two storage class away from the default and both Kafka and Zookeeper accepted the changed value.
<img width="321" alt="Screenshot 2023-05-05 at 18 27 27" src="https://user-images.githubusercontent.com/51744616/236526879-b3462706-ec92-4a1b-a52c-5c7f4c9150f5.png">

See [this internal slack thread](https://ibm-watson-iot.slack.com/archives/C040TETRV2T/p1681819086959789?thread_ts=1681809067.685299&cid=C040TETRV2T) for more details

@sauraba Given it looks to be solved I'm going to close this issue out for now but feel free to reopen it if the issue persists
