### ISSUE TITLE
For OCP release mirror, the QUAY_USERNAME and QUAY_PASSWORD environment variables are required

### ISSUE THREAD

**Issue by hughjfchen** [ibm-mas/installer#86]
The `functions/mirror_to_registry` script should check the `QUAY_USERNAME` and `QUAY_PASSWORD` environment variables
with `--mirror-redhat-release` option. Otherwise, the playbook will thrown an error complaining these two environment variables not present during running.

**Comment by durera** [comment]
This has been addressed under #90 the playbook/role/CLI command now asks for the user to provide the location to the pull secret (https://console.redhat.com/openshift/install/pull-secret) ... rather than requiring them to enter all the credentials directly.

This also avoids confusion with certain images that are only available when using one of these pull secrets, and are not available using a "normal" Red Hat username/password.
