### ISSUE TITLE
Reinstall of MAS instance is failing after a successful uninstall of previous MAS instance

### ISSUE THREAD

**Issue by NatarajBTI** [ibm-mas/installer#868]
Reinstall of MAS instance is failing at common-services task after a successful uninstall of previous MAS instance using MAS client command: mas uninstall -i inst1 --no-confirm
It's getting stuck at below phase (where it waits for Founcational Service) and is exhausting all retries and failing.
TASK [ibm.mas_devops.common_services : Wait for Foundational Services resources to be ready (60s delay)] ***

We are using MAS client approach for both install & uninstall of MAS instance.

Note: We were able to proceed with reinstall after deleting Certificate CRD used by CertManager.

**Comment by andrercm** [comment]
The fix is all about including `Certificate` CRD to be deleted in `cert_manager` role during `uninstall` action. Without that, during common services reinstall, ibm common services operator will lookup `Certificate` CRD and will find it and think certmanager is installed and call cert manager webhook pod (which is not present because it was deleted during certmanager uninstall) and then fail to proceed with ibm-common-services reinstall...

**Comment by andrercm** [comment]
Also another thing to consider while fixing this issue is that Certificate Manager is a cluster wide dependency... so uninstalling it as part of a MAS instance uninstall my compromise other MAS instances or dependencies installed in the same cluster... shouldn't we allow option to skip uninstalling certmanager when uninstalling a MAS instance, instead of **always** uninstalling certmanager along with MAS instance?

**Comment by whitfiea** [comment]
@andrercm is this just an issue with common-services? If we used the redhat cert-manager does that operator get into the same state as the CRD is there?

Also don't we already provide the ability to control if the cert-mnager should be uninstalled or not in the cli? https://github.com/ibm-mas/cli/blob/ecc72f6c23a8b2f30b9e366500daa7ec08cd9ad0/image/cli/mascli/functions/uninstall#L40

**Comment by andrercm** [comment]
@whitfiea from what I could understand looking at the cluster they faced the problem, the issue is that IBM Common Services operator finds the Certificate CRD present, and based on that assumes CertManager is installed and fails to call cert-manager-webhook pod. As it fails at this point, IBM Common Services operator does not go further and install the remaining deployments for ODLM and NamespaceScope operators, thus eventually the entire common services role fails.

Also on the CertManager uninstall via cli, I do see that we prompt for confirming to uninstall if using the interactive mode, but i don't see an argument available to uninstall/skip it via non-interactive mode... i guess thought if you `export CERT_MANAGER_ACTION=uninstall` (or not) that might control it whether you want to have it installed or not.

**Comment by andrercm** [comment]
Fix should be available with this [PR](https://github.com/ibm-mas/ansible-devops/pull/1262)

Preview of the fix can be tested using `cli:7.19.0-pre.mas-uninstall-fixes`
