### ISSUE TITLE
For OCP release mirror, the quay_username and quay_password are required

### ISSUE THREAD

**Issue by hughjfchen** [ibm-mas/installer#88]
For `OCP release` mirror, the `QUAY_USERNAME` and `QUAY_PASSWORD` are required. Doc should make that clear.

**Comment by hughjfchen** [comment]
I think the command line `mas mirror-images` should check the `QUAY_USERNAME` and `QUAY_PASSWORD`
for `mirror-ocp-release` and prompt for it if not presented.

**Comment by hughjfchen** [comment]
OK. I guess this should be submitted to the `ibm-mas/cli` repository.

**Comment by durera** [comment]
Working on a fix for this now :+1:

**Comment by durera** [comment]
This has been addressed under https://github.com/ibm-mas/cli/pull/90 the playbook/role/CLI command now asks for the user to provide the location to the pull secret (https://console.redhat.com/openshift/install/pull-secret) ... rather than requiring them to enter all the credentials directly.

https://ibm-mas.github.io/ansible-devops/roles/mirror_ocp_release/#redhat_pullsecret

This also avoids confusion with certain images that are only available when using one of these pull secrets, and are not available using a "normal" Red Hat username/password.
