### ISSUE TITLE
Support ability to customize storage classes across mas install, instead of using unique RWO and RWX across the pipeline

### ISSUE THREAD

**Issue by andrercm** [ibm-mas/installer#930]
This is already supported in ansible-devops, but in cli we just define one RWO and RWX storage class across the pipeline.

This has been a request for enhancement brought by two business partners that are active contributors and users of our automation engine.

**Comment by durera** [comment]
To what end?  What's the use case we have in mind where there's sufficient difference in the storage requirements that one thing that needs RWX and another that also needs RWX would be configured with two different storage classes?  Just because we can doesn't always mean we (or our business partners) should, there may be a good reason for supporting this, but I'd like to have that reason clearly defined to justify the extra complexity it brings, which IMO provides minimal value.

**Comment by GuilhermeFAC** [comment]
@andrercm @durera Good afternoon

for example, development environments, I would just like to leave the db2 storage with 10iops and the rest of the applications with 5 iops, 10 iops for everything is very expensive, not to mention the need for, for example, doclinks to have 10 iops, jms, uds etc. development only db2 with high iops. If it is possible, then being able to select the db2 storage class separately from the others would help with mascli.

**Comment by durera** [comment]
I'm going to close this as duplicate of https://github.com/ibm-mas/cli/issues/1037 where we have agreed to add support for specific db2 storage class override for Db2 which was the example given here:

> If it is possible, then being able to select the db2 storage class separately from the others would help with mascli.
